/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mabomba2b;

/**
 *
 * @author geekaia
 */
public class CALCULOS extends javax.swing.JFrame {

    public void objetivoManter(){
        btnManter.setSelected(true);
        btnEngordar.setSelected(false);
        btnEmagrecer.setSelected(false);
    }
    public void objetivoEngordar(){
        btnManter.setSelected(false);
        btnEngordar.setSelected(true);
        btnEmagrecer.setSelected(false);
    } 
    public void objetivoEmagrecer(){
        btnManter.setSelected(false);
        btnEngordar.setSelected(false);
        btnEmagrecer.setSelected(true);
    }
    public void paraMasculino(){
        btnMasculino.setSelected(true);
        btnFeminino.setSelected(false);
    }
    public void paraFeminino(){
        btnMasculino.setSelected(false);
        btnFeminino.setSelected(true);
    }
    /**
     * Creates new form CALCULOS
     */
    public CALCULOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        lbResultado = new javax.swing.JLabel();
        btnCalcIMC = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPesoCalorias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnManter = new javax.swing.JToggleButton();
        btnEngordar = new javax.swing.JToggleButton();
        btnEmagrecer = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        btnMasculino = new javax.swing.JToggleButton();
        btnFeminino = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JSpinner();
        lbResultadoCalorias = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Peso");

        jLabel2.setText("Altura");

        lbResultado.setText("Situação:");

        btnCalcIMC.setText("Calcular");
        btnCalcIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcIMCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPeso)
                    .addComponent(txtAltura)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbResultado)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnCalcIMC, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbResultado)
                .addGap(57, 57, 57)
                .addComponent(btnCalcIMC)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("IMC", jPanel1);

        jLabel3.setText("Peso");

        jLabel4.setText("Objetivo");

        btnManter.setSelected(true);
        btnManter.setText("Manter");
        btnManter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManterActionPerformed(evt);
            }
        });

        btnEngordar.setSelected(true);
        btnEngordar.setText("Engordar");
        btnEngordar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEngordarActionPerformed(evt);
            }
        });

        btnEmagrecer.setSelected(true);
        btnEmagrecer.setText("Emagrecer");
        btnEmagrecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmagrecerActionPerformed(evt);
            }
        });

        jLabel5.setText("Sexo");

        btnMasculino.setSelected(true);
        btnMasculino.setText("Masculino");
        btnMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasculinoActionPerformed(evt);
            }
        });

        btnFeminino.setSelected(true);
        btnFeminino.setText("Feminino");
        btnFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemininoActionPerformed(evt);
            }
        });

        jLabel6.setText("Idade");

        lbResultadoCalorias.setText("Resultado:");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResultadoCalorias)
                    .addComponent(jLabel6)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFeminino))
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnManter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEngordar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEmagrecer))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(txtPesoCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnCalcular)
                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesoCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManter)
                    .addComponent(btnEngordar)
                    .addComponent(btnEmagrecer))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMasculino)
                    .addComponent(btnFeminino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbResultadoCalorias)
                .addGap(27, 27, 27)
                .addComponent(btnCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CALORIAS", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcIMCActionPerformed
        // TODO add your handling code here:
        String peso  = txtPeso.getText();  
        String altura  = txtAltura.getText();  
        
        try { 
            double pesod = Double.parseDouble(peso);
            double alturad = Double.parseDouble(altura);
            double imcRes = pesod / (alturad*alturad);
            
            String strSit=""; 
            if (imcRes < 18.5) { 
                strSit = "Abaixo do peso"; 
            } else if(imcRes <= 24.9) { 
                strSit = "Peso normal"; 
            } else if(imcRes <= 29.9) { 
                strSit = "Pré-obesidade"; 
            } else if(imcRes <= 34.9) { 
                strSit = "Obesidade Grau 1"; 
            } else if(imcRes <= 39.9) { 
                strSit = "Obesidade Grau 2"; 
            } else {
                strSit = "Obesidade Grau 3"; 
            }
              lbResultado.setText("Situação: "+strSit);  
        }catch(Exception e) { 
            e.printStackTrace();
            lbResultado.setText("Situação: ERRO NA CONVERSÃO");
        }
    }//GEN-LAST:event_btnCalcIMCActionPerformed

    private void btnManterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManterActionPerformed
        // TODO add your handling code here:
        objetivoManter(); 
    }//GEN-LAST:event_btnManterActionPerformed

    private void btnEngordarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEngordarActionPerformed
        // TODO add your handling code here:
        objetivoEngordar();
    }//GEN-LAST:event_btnEngordarActionPerformed

    private void btnEmagrecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmagrecerActionPerformed
        // TODO add your handling code here:
        objetivoEmagrecer();
    }//GEN-LAST:event_btnEmagrecerActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here: 
       String sexopessoa="Nulo"; 
       
       if (btnMasculino.isSelected()) { 
           sexopessoa="M"; 
       } else if(btnFeminino.isSelected()) {
           sexopessoa="F";            
       }
       System.out.println("Sexo: "+sexopessoa);
       String idade = txtIdade.getValue().toString(); 
       Integer idadei = Integer.parseInt(idade); 
       String peso = txtPesoCalorias.getText();
       Double pesod = Double.parseDouble(peso); 
        double gastoEnergbasal=0.0;
       if (idadei >= 0 && idadei <= 3) {
           if (sexopessoa.equals("F") ){
               gastoEnergbasal = (58.317 * pesod) - 31.1; 
           } else if (sexopessoa.equals("M") ){
               gastoEnergbasal = (59.512 * pesod) - 30.4;  
           }
       } else if ( idadei <= 10) {
           if (sexopessoa.equals("F") ){
               gastoEnergbasal = (20.315 * pesod) - 485.9; 
           } else if (sexopessoa.equals("M") ){
               gastoEnergbasal = (22.706 * pesod) - 504.3;  
           }
       }
       lbResultadoCalorias.setText("Gasto Basal: "+gastoEnergbasal);
 


    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasculinoActionPerformed
        // TODO add your handling code here:
        paraMasculino();
    }//GEN-LAST:event_btnMasculinoActionPerformed

    private void btnFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemininoActionPerformed
        // TODO add your handling code here:
        paraFeminino();
    }//GEN-LAST:event_btnFemininoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CALCULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CALCULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CALCULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CALCULOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CALCULOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcIMC;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JToggleButton btnEmagrecer;
    private javax.swing.JToggleButton btnEngordar;
    private javax.swing.JToggleButton btnFeminino;
    private javax.swing.JToggleButton btnManter;
    private javax.swing.JToggleButton btnMasculino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbResultadoCalorias;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JSpinner txtIdade;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPesoCalorias;
    // End of variables declaration//GEN-END:variables
}
